# 
# WRITE DRC WAIVERS 

current_instance -quiet
create_waiver -type DRC -id {REQP-2057} -desc "drc_waiver1" -objects [get_cells { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_0/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT[0].MBUFG_GT_U }] -objects [get_pins { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_0/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT[0].MBUFG_GT_U/CLR }] -objects [get_cells { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_0/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT_SYNC[0].BUFG_GT_SYNC_U }] -objects [get_pins { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_0/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT[0].MBUFG_GT_U/CLRB_LEAF }] -timestamp "Wed Feb 14 15:13:28 GMT 2024" ;#1
create_waiver -type DRC -id {REQP-2057} -desc "drc_waiver2" -objects [get_cells { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_1/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT[0].MBUFG_GT_U }] -objects [get_pins { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_1/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT[0].MBUFG_GT_U/CLR }] -objects [get_cells { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_1/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT_SYNC[0].BUFG_GT_SYNC_U }] -objects [get_pins { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_1/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT[0].MBUFG_GT_U/CLRB_LEAF }] -timestamp "Wed Feb 14 15:13:48 GMT 2024" ;#2
create_waiver -type DRC -id {REQP-2057} -desc "drc_waiver3" -objects [get_cells { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_1_1/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT[0].MBUFG_GT_U }] -objects [get_pins { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_1_1/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT[0].MBUFG_GT_U/CLR }] -objects [get_cells { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_1_1/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT_SYNC[0].BUFG_GT_SYNC_U }] -objects [get_pins { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_1_1/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT[0].MBUFG_GT_U/CLRB_LEAF }] -timestamp "Wed Feb 14 15:13:59 GMT 2024" ;#3
create_waiver -type DRC -id {REQP-2057} -desc "drc_waiver4" -objects [get_cells { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_1_2/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT[0].MBUFG_GT_U }] -objects [get_pins { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_1_2/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT[0].MBUFG_GT_U/CLR }] -objects [get_cells { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_1_2/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT_SYNC[0].BUFG_GT_SYNC_U }] -objects [get_pins { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_1_2/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT[0].MBUFG_GT_U/CLRB_LEAF }] -timestamp "Wed Feb 14 15:14:10 GMT 2024" ;#4
create_waiver -type DRC -id {REQP-2057} -desc "drc_waiver5" -objects [get_cells { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_1_3/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT[0].MBUFG_GT_U }] -objects [get_pins { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_1_3/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT[0].MBUFG_GT_U/CLR }] -objects [get_cells { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_1_3/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT_SYNC[0].BUFG_GT_SYNC_U }] -objects [get_pins { top_i/ulp/mrmac_bd_1/inst/mbufg_gt_1_3/U0/USE_MBUFG_GT_SYNC.GEN_MBUFG_GT[0].MBUFG_GT_U/CLRB_LEAF }] -timestamp "Wed Feb 14 15:14:24 GMT 2024" ;#5

# 
current_instance -quiet
